import dashboard from "./assets/navigation/dashboard.svg";
import portfolio from "./assets/navigation/portfolio.svg";
import carbon_wallet from "./assets/navigation/carbon_wallet.svg";
import user from "./assets/navigation/user.svg";
import help from "./assets/navigation/help.svg";
import settings from "./assets/settings.svg";
import logout from "./assets/navigation/logout.svg";
import logolight from "./assets/logolight.png";
import bronze from "@/assets/bronze.svg";
import silver from "@/assets/silver.svg";
import gold from "@/assets/gold.svg";
import platinum from "@/assets/platinum.svg";
import MintCarbon from "@/assets/navigation/mintCarbon.svg";
import certificate from "@/assets/certificate.svg";
const sidebar = {
  logo: logolight,
  navigation: [
    {
      label: "Dashboard",
      icon: dashboard,
      route: "/",
    },
    {
      label: "Portfolio",
      icon: portfolio,
      route: "/portfolio",
    },
    {
      label: "Wallet",
      icon: carbon_wallet,
      route: "/wallet",
    },
    {
      label: "Mint Carbon",
      icon: MintCarbon,
      route: "/MintCarbonCredits",
    },
    {
      label: "Carbon Registry",
      icon: certificate,
      route: "/carbon-credit-registry",
    },
    {
      label: "Membership",
      icon: user,
      route: "/membership",
    },
    {
      label: "Settings",
      icon: settings,
      route: "/settings",
    },
  ],
  footernav: [
    {
      label: "Help",
      icon: help,
      route: "/help",
    },
    {
      label: "Logout",
      icon: logout,
      route: "/logout",
    },
  ],
};

const plans = [
  {
    id: 1,
    image: bronze,
    name: "Bronze",
    amount: "1M",
    tokenName: "XCB",
    discount: "1% Fee Discount",
    benefits: ["Basic Customer Support", "Monthly Reports"],
  },
  {
    id: 2,
    image: silver,
    name: "Silver",
    amount: "2.5M",
    tokenName: "XCB",
    discount: "2.5% Fee Discount",
    benefits: ["Basic Customer Support", "Monthly Reports"],
  },
  {
    id: 3,
    image: gold,
    name: "Gold",
    amount: "5M",
    tokenName: "XCB",
    discount: "5% Fee Discount",
    benefits: ["Basic Customer Support", "Monthly Reports"],
  },
  {
    id: 4,
    image: platinum,
    name: "Platinum",
    amount: "10M",
    tokenName: "XCB",
    discount: "10% Fee Discount",
    benefits: ["Basic Customer Support", "Monthly Reports"],
  },
];

const tabData = {
  open: {
    title: "Open Positions",
    columns: ["Assets", "Quantity", "Market Value", "Cost Basis"],
    keys: ["assets", "quantity", "marketvalue", "costbasis"],
    items: [
      {
        id: 1,
        assets: "Reforest Brazil",
        quantity: "5.000",
        marketvalue: "$43.00",
        costbasis: "62.00",
      },

      {
        id: 2,
        assets: "Reforest Brazil",
        quantity: "5.000",
        marketvalue: "$43.00",
        costbasis: "62.00",
      },

      {
        id: 3,
        assets: "Reforest Brazil",
        quantity: "5.000",
        marketvalue: "$43.00",
        costbasis: "62.00",
      },

      {
        id: 4,
        assets: "Reforest Brazil",
        quantity: "5.000",
        marketvalue: "$43.00",
        costbasis: "62.00",
      },

      {
        id: 5,
        assets: "Reforest Brazil",
        quantity: "5.000",
        marketvalue: "$43.00",
        costbasis: "62.00",
      },
    ],
  },
  historical: {
    title: "Historical Trades",
    columns: ["Trade ID", "Trade Name", "Date", "Result"],
    keys: ["tradeId", "tradeName", "date", "result"],
    items: [
      {
        tradeId: 101,
        tradeName: "AAPL Buy",
        date: "2024-03-21",
        result: "Profit",
      },
      {
        tradeId: 102,
        tradeName: "GOOGL Sell",
        date: "2024-04-15",
        result: "Loss",
      },
    ],
  },
  pending: {
    title: "Pending Contracts",
    columns: ["Contract Name", "Due Date"],
    keys: ["contractName", "due"],
    items: [
      { contractName: "Contract A", due: "2025-06-15" },
      { contractName: "Contract B", due: "2025-07-01" },
    ],
  },
};

const tokenBalance = [
  {
    tokenName: "$XCB Token",
    amount: "12,000",
  },
  {
    tokenName: "Carbon Credit - Reforest Brazil",
    status: "sale",
    amount: "5000",
  },
  {
    tokenName: "ESG Asset - Wind Africa",
    status: "withdraw",
    amount: "1200",
  },
];

//   Dummy data for History
const DummyData = [
  {
    date: "2025-05-01",
    plan: "Bronze",
    type: "Deposit",
    amount: "5000",
    status: "Confirmed",
    tx: "0x3a5f...e9d Tx",
  },
  {
    date: "2025-05-01",
    plan: "Bronze",
    type: "Deposit",
    amount: "5000",
    status: "Confirmed",
    tx: "0x3a5f...e9d Tx",
  },
  {
    date: "2025-05-01",
    plan: "Bronze",
    type: "Deposit",
    amount: "5000",
    status: "Confirmed",
    tx: "0x3a5f...e9d Tx",
  },
];

// Contract Delivery Schedule

const deliverySchedule = [
  {
    contractId: "#AG-2030",
    asset: "Bronze",
    nextDelivery: "Deposit",
    totalDeliveries: "3/12",
    status: "Confirmed",
  },
];

// Data for dashboard
const marketplace = [
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
  {
    assetName: "VCS-FORESTRY",
    date: "Brazil Project 2021",
    projectType: "Forestry",
    insuranceYear: "2023",
    location: "Brazil",
    registry: "Verra (VCS)",
    price: "$12.75",
    availableVolume: "45,123",
    supplier: "GreenEarth Corp",
    vintage: "2020",
    quantity: "25",
    action: "BUY",
    createdDate: "2023-08-10T09:15:32.123Z",
  },
  {
    assetName: "GS-RENEWABLE",
    date: "India Project 2022",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Gold Standard",
    price: "$18.50",
    availableVolume: "72,890",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "50",
    action: "SELL",
    createdDate: "2024-03-22T17:45:01.456Z",
  },
  {
    assetName: "ACR-METHANE",
    date: "US Project 2019",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$9.25",
    availableVolume: "15,678",
    supplier: "CarbonNeutral Inc",
    vintage: "2019",
    quantity: "30",
    action: "BUY",
    createdDate: "2023-11-05T03:20:19.789Z",
  },
  {
    assetName: "CAR-SOIL",
    date: "Australia Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2024",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$15.80",
    availableVolume: "88,456",
    supplier: "Sustainable Futures",
    vintage: "2023",
    quantity: "40",
    action: "SELL",
    createdDate: "2025-01-15T12:10:45.234Z",
  },
  {
    assetName: "VCS-AFFORESTATION",
    date: "Kenya Project 2020",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Kenya",
    registry: "Verra (VCS)",
    price: "$11.90",
    availableVolume: "33,214",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "20",
    action: "BUY",
    createdDate: "2023-06-30T20:55:28.567Z",
  },
  {
    assetName: "GS-FORESTRY",
    date: "Indonesia Project 2018",
    projectType: "Forestry",
    insuranceYear: "2019",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$14.60",
    availableVolume: "60,789",
    supplier: "GreenEarth Corp",
    vintage: "2018",
    quantity: "35",
    action: "SELL",
    createdDate: "2024-09-12T06:25:13.890Z",
  },
  {
    assetName: "ACR-RENEWABLE",
    date: "Canada Project 2024",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Canada",
    registry: "American Carbon Registry",
    price: "$17.45",
    availableVolume: "25,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2024",
    quantity: "45",
    action: "BUY",
    createdDate: "2025-04-08T15:40:57.123Z",
  },
  {
    assetName: "CAR-METHANE",
    date: "Brazil Project 2021",
    projectType: "Methane Capture",
    insuranceYear: "2020",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$10.30",
    availableVolume: "50,987",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "15",
    action: "BUY",
    createdDate: "2023-12-25T22:05:36.456Z",
  },
  {
    assetName: "VCS-SOIL",
    date: "India Project 2023",
    projectType: "Soil Carbon",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$16.25",
    availableVolume: "77,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2022",
    quantity: "60",
    action: "SELL",
    createdDate: "2024-07-19T11:30:24.789Z",
  },
  {
    assetName: "GS-AFFORESTATION",
    date: "Kenya Project 2019",
    projectType: "Afforestation",
    insuranceYear: "2024",
    location: "Kenya",
    registry: "Gold Standard",
    price: "$13.70",
    availableVolume: "40,321",
    supplier: "ClimateWorks",
    vintage: "2019",
    quantity: "28",
    action: "BUY",
    createdDate: "2023-09-03T04:15:49.012Z",
  },
  {
    assetName: "ACR-FORESTRY",
    date: "US Project 2022",
    projectType: "Forestry",
    insuranceYear: "2020",
    location: "US",
    registry: "American Carbon Registry",
    price: "$19.10",
    availableVolume: "65,432",
    supplier: "GreenEarth Corp",
    vintage: "2021",
    quantity: "33",
    action: "SELL",
    createdDate: "2024-02-14T18:50:11.345Z",
  },
  {
    assetName: "CAR-RENEWABLE",
    date: "Australia Project 2020",
    projectType: "Renewable Energy",
    insuranceYear: "2023",
    location: "Australia",
    registry: "Climate Action Reserve",
    price: "$8.95",
    availableVolume: "20,876",
    supplier: "EcoSolutions Ltd",
    vintage: "2020",
    quantity: "22",
    action: "BUY",
    createdDate: "2025-06-01T08:35:26.678Z",
  },
  {
    assetName: "VCS-METHANE",
    date: "Canada Project 2018",
    projectType: "Methane Capture",
    insuranceYear: "2019",
    location: "Canada",
    registry: "Verra (VCS)",
    price: "$14.85",
    availableVolume: "55,789",
    supplier: "Sustainable Futures",
    vintage: "2018",
    quantity: "48",
    action: "SELL",
    createdDate: "2023-05-17T13:20:42.901Z",
  },
  {
    assetName: "GS-SOIL",
    date: "Indonesia Project 2024",
    projectType: "Soil Carbon",
    insuranceYear: "2022",
    location: "Indonesia",
    registry: "Gold Standard",
    price: "$12.40",
    availableVolume: "30,654",
    supplier: "CarbonNeutral Inc",
    vintage: "2023",
    quantity: "37",
    action: "BUY",
    createdDate: "2024-10-29T21:45:58.234Z",
  },
  {
    assetName: "ACR-AFFORESTATION",
    date: "Kenya Project 2021",
    projectType: "Afforestation",
    insuranceYear: "2020",
    location: "Kenya",
    registry: "American Carbon Registry",
    price: "$16.90",
    availableVolume: "85,123",
    supplier: "ClimateWorks",
    vintage: "2021",
    quantity: "55",
    action: "SELL",
    createdDate: "2023-07-08T02:10:14.567Z",
  },
  {
    assetName: "CAR-FORESTRY",
    date: "Brazil Project 2019",
    projectType: "Forestry",
    insuranceYear: "2024",
    location: "Brazil",
    registry: "Climate Action Reserve",
    price: "$11.20",
    availableVolume: "42,567",
    supplier: "GreenEarth Corp",
    vintage: "2019",
    quantity: "29",
    action: "BUY",
    createdDate: "2024-04-23T16:25:39.890Z",
  },
  {
    assetName: "VCS-RENEWABLE",
    date: "India Project 2023",
    projectType: "Renewable Energy",
    insuranceYear: "2021",
    location: "India",
    registry: "Verra (VCS)",
    price: "$18.75",
    availableVolume: "70,432",
    supplier: "EcoSolutions Ltd",
    vintage: "2022",
    quantity: "44",
    action: "SELL",
    createdDate: "2025-02-16T10:40:55.123Z",
  },
  {
    assetName: "GS-METHANE",
    date: "US Project 2020",
    projectType: "Methane Capture",
    insuranceYear: "2023",
    location: "US",
    registry: "Gold Standard",
    price: "$10.50",
    availableVolume: "28,901",
    supplier: "Sustainable Futures",
    vintage: "2020",
    quantity: "31",
    action: "BUY",
    createdDate: "2023-10-11T05:55:10.456Z",
  },
  {
    assetName: "ACR-SOIL",
    date: "Australia Project 2022",
    projectType: "Soil Carbon",
    insuranceYear: "2019",
    location: "Australia",
    registry: "American Carbon Registry",
    price: "$15.35",
    availableVolume: "62,345",
    supplier: "CarbonNeutral Inc",
    vintage: "2021",
    quantity: "52",
    action: "SELL",
    createdDate: "2024-08-04T19:30:25.789Z",
  },
  {
    assetName: "CAR-AFFORESTATION",
    date: "Canada Project 2024",
    projectType: "Afforestation",
    insuranceYear: "2022",
    location: "Canada",
    registry: "Climate Action Reserve",
    price: "$13.25",
    availableVolume: "35,876",
    supplier: "ClimateWorks",
    vintage: "2023",
    quantity: "27",
    action: "BUY",
    createdDate: "2025-05-27T14:15:40.012Z",
  },
];

const newsESG = [
  {
    tag: "ESG",
    timeLabel: "Time",
    title: "EU Proposes New Green Bond Standard",
    timeLabel: "15 min ago",
    description:
      "The European Commission introduced a proposal that aims to standardize green bond issuance across member states.",
  },
  {
    tag: "ESG",
    timeLabel: "Time",
    title: "EU Proposes New Green Bond Standard",
    timeLabel: "15 min ago",
    description:
      "The European Commission introduced a proposal that aims to standardize green bond issuance across member states.",
  },
  {
    tag: "ESG",
    timeLabel: "Time",
    title: "EU Proposes New Green Bond Standard",
    timeLabel: "15 min ago",
    description:
      "The European Commission introduced a proposal that aims to standardize green bond issuance across member states.",
  },
  {
    tag: "ESG",
    timeLabel: "Time",
    title: "EU Proposes New Green Bond Standard",
    timeLabel: "15 min ago",
    description:
      "The European Commission introduced a proposal that aims to standardize green bond issuance across member states.",
  },
];

const newsMajorTrades = [
  {
    tag: "Major Trades",
    timeLabel: "Time",
    title: "Tech Stocks Lead Market Rally",
    timeLabel: "15 min ago",
    description:
      "Major tech companies saw a surge in share prices after favorable earnings reports were released.",
  },
  {
    tag: "Major Trades",
    timeLabel: "Time",
    title: "Tech Stocks Lead Market Rally",
    timeLabel: "15 min ago",
    description:
      "Major tech companies saw a surge in share prices after favorable earnings reports were released.",
  },
  {
    tag: "Major Trades",
    timeLabel: "Time",
    title: "Tech Stocks Lead Market Rally",
    timeLabel: "15 min ago",
    description:
      "Major tech companies saw a surge in share prices after favorable earnings reports were released.",
  },
  {
    tag: "Major Trades",
    timeLabel: "Time",
    title: "Tech Stocks Lead Market Rally",
    timeLabel: "15 min ago",
    description:
      "Major tech companies saw a surge in share prices after favorable earnings reports were released.",
  },
];

const newsRegulatory = [
  {
    tag: "Regulatory",
    timeLabel: "Time",
    title: "SEC Announces Crypto Exchange Crackdown",
    timeLabel: "15 min ago",
    description:
      "The SEC has intensified scrutiny on decentralized exchanges, citing investor protection concerns.",
  },
  {
    tag: "Regulatory",
    timeLabel: "Time",
    title: "SEC Announces Crypto Exchange Crackdown",
    timeLabel: "15 min ago",
    description:
      "The SEC has intensified scrutiny on decentralized exchanges, citing investor protection concerns.",
  },
  {
    tag: "Regulatory",
    timeLabel: "Time",
    title: "SEC Announces Crypto Exchange Crackdown",
    timeLabel: "15 min ago",
    description:
      "The SEC has intensified scrutiny on decentralized exchanges, citing investor protection concerns.",
  },
  {
    tag: "Regulatory",
    timeLabel: "Time",
    title: "SEC Announces Crypto Exchange Crackdown",
    timeLabel: "15 min ago",
    description:
      "The SEC has intensified scrutiny on decentralized exchanges, citing investor protection concerns.",
  },
];

const formFields = [
  {
    label: "Project Name",
    name: "projectName",
    placeholder: "Mangrove Reforestation Initiative - Indonesia",
  },
  {
    label: "Project Type",
    name: "type",
    placeholder: "Mangrove Reforestation Initiative - Indonesia",
  },
  {
    label: "Vintage & Issuance Years",
    name: "vintageYear",
    placeholder: "2022-2024",
  },
  {
    label: "Total Tonnes",
    name: "quantity",
    placeholder: "25,000 tCO₂e",
  },
  {
    label: "Location",
    name: "location",
    placeholder: "Kalimantan, Indonesia",
  },
  {
    label: "Certification Status",
    name: "status",
    placeholder: "Verified & Issued",
  },
  {
    label: "Verification Body",
    name: "verificationBody",
    placeholder: "DNV GL",
  },
  {
    label: "Serial Number Range",
    name: "serialNumberRange",
    placeholder: "VCS-123456-123456-123456-1-25000",
  },
  {
    label: "Project Developer",
    name: "project_developer",
    placeholder: "EcoForest Partners",
  },
];

const impactTags = [
  {
    id: 1,
    tag: "SDG 13: Climate Action",
  },
  {
    id: 2,
    tag: "SDG 15: Life on Land",
  },
  {
    id: 3,
    tag: "SDG 8: Decent Work",
  },
  {
    id: 4,
    tag: "SDG 1: No Poverty",
  },
];

const portfolioData = {
  openPositions: {
    title: "Open Positions",
    data: [
      {
        assetName: "Amazon Rainforest Conservation",
        projectType: "REDD+",
        quantity: "10,000",
        marketValue: "$150,000",
        costBasis: "$140,000",
        vintage: "2023",
        location: "Brazil",
        status: "Active",
        date: "2024-03-15",
      },
      {
        assetName: "Wind Farm Project",
        projectType: "Renewable Energy",
        quantity: "5,000",
        marketValue: "$75,000",
        costBasis: "$70,000",
        vintage: "2024",
        location: "India",
        status: "Active",
        date: "2024-03-10",
      },
      {
        assetName: "Mangrove Restoration",
        projectType: "Blue Carbon",
        quantity: "8,000",
        marketValue: "$120,000",
        costBasis: "$110,000",
        vintage: "2023",
        location: "Indonesia",
        status: "Active",
        date: "2024-02-28",
      },
    ],
  },
  historicalTrades: {
    title: "Historical Trades",
    data: [
      {
        tradeId: "TR-2024-001",
        assetName: "Solar Power Project",
        projectType: "Renewable Energy",
        quantity: "3,000",
        tradedValue: "$42,000",
        tradeType: "Buy",
        date: "2024-01-15",
        status: "Completed",
      },
      {
        tradeId: "TR-2024-002",
        assetName: "Forest Conservation",
        projectType: "REDD+",
        quantity: "5,000",
        tradedValue: "$70,000",
        tradeType: "Sell",
        date: "2024-02-01",
        status: "Completed",
      },
      {
        tradeId: "TR-2024-003",
        assetName: "Methane Capture",
        projectType: "Industrial Gas",
        quantity: "2,000",
        tradedValue: "$28,000",
        tradeType: "Buy",
        date: "2024-02-15",
        status: "Completed",
      },
    ],
  },
  pendingContracts: {
    title: "Pending Contracts",
    data: [
      {
        contractId: "CT-2024-001",
        assetName: "Reforestation Project",
        projectType: "Forestry",
        quantity: "7,000",
        value: "$98,000",
        dueDate: "2024-04-30",
        status: "Pending Approval",
      },
      {
        contractId: "CT-2024-002",
        assetName: "Hydroelectric Plant",
        projectType: "Renewable Energy",
        quantity: "4,000",
        value: "$56,000",
        dueDate: "2024-05-15",
        status: "Under Review",
      },
    ],
  },
};

const activeAgreements = {
  title: "Active Agreements",
  data: [
    {
      agreementId: "AG-2024-001",
      assetName: "Amazon Rainforest Conservation",
      projectType: "REDD+",
      nextDelivery: "2024-04-15",
      totalDeliveries: "4/12",
      quantity: "2,500",
      status: "On Track",
      vintage: "2023",
    },
    {
      agreementId: "AG-2024-002",
      assetName: "Wind Farm Project",
      projectType: "Renewable Energy",
      nextDelivery: "2024-04-30",
      totalDeliveries: "2/6",
      quantity: "1,000",
      status: "On Track",
      vintage: "2024",
    },
    {
      agreementId: "AG-2024-003",
      assetName: "Mangrove Restoration",
      projectType: "Blue Carbon",
      nextDelivery: "2024-05-15",
      totalDeliveries: "1/4",
      quantity: "2,000",
      status: "Pending",
      vintage: "2023",
    },
  ],
};

const portlioOption = [
  {
    lable: "Open Positions",
    value: "open_positions",
  },
  {
    lable: "Historical trades",
    value: "historical_trades",
  },
  {
    lable: "Pending Monthly Contracts",
    value: "pending_contracts",
  },
];

const projects = [
  {
    label: "Rainforest Protection Project - VCS-123456-2022",
    value: "vcs-123456-2022",
  },
  {
    label: "Mangrove Restoration Initiative - VCS-654321-2023",
    value: "vcs-654321-2023",
  },
];

const reasonsWithdrawl = [
  {
    label: "Transfer of ownership",
    value: "transfer_of_ownership",
  },
  {
    label: "Dont want to continue anymore",
    value: "dont_want_to_continue",
  },
];

const projectDetails = [
  { label: "Project Type", value: "Rainforest Protection Project" },
  { label: "Vintage Year", value: "2022" },
  { label: "Total Tonnes", value: "5,000 tCO₂e" },
  { label: "Registry", value: "Verra" },
];

const notifications = [
  {
    id: 1,
    type: "transaction",
    title: "Transaction Completed",
    message:
      "Your purchase of 100 carbon credits has been completed successfully. The transaction has been recorded on the blockchain and the credits have been added to your portfolio.",
    date: "2024-03-20T10:30:00",
    read: false,
  },
  {
    id: 2,
    type: "system",
    title: "System Maintenance",
    message:
      "Scheduled maintenance will occur on March 25th at 02:00 UTC. The platform will be unavailable for approximately 2 hours.",
    date: "2024-03-19T15:45:00",
    read: true,
  },
  // Add more sample notifications as needed
];

export {
  sidebar,
  plans,
  tabData,
  DummyData,
  tokenBalance,
  deliverySchedule,
  marketplace,
  newsESG,
  newsMajorTrades,
  newsRegulatory,
  formFields,
  impactTags,
  portfolioData,
  portlioOption,
  projects,
  reasonsWithdrawl,
  projectDetails,
  activeAgreements,
  notifications,
};
